SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [etl].[crm_account_migration_update_20160930] AS

SELECT ab.AccountId ,
       ab.AccountCategoryCode ,
       ab.TerritoryId ,
       ab.DefaultPriceLevelId ,
       ab.CustomerSizeCode ,
       ab.PreferredContactMethodCode ,
       ab.CustomerTypeCode ,
       ab.AccountRatingCode ,
       ab.IndustryCode ,
       ab.TerritoryCode ,
       ab.AccountClassificationCode ,
       ab.BusinessTypeCode ,
       ab.OwningBusinessUnit ,
       ab.OriginatingLeadId ,
       ab.PaymentTermsCode ,
       ab.ShippingMethodCode ,
       ab.PrimaryContactId ,
       ab.ParticipatesInWorkflow ,
       ab.Name ,
       ab.AccountNumber ,
       ab.Revenue ,
       ab.NumberOfEmployees ,
       ab.Description ,
       ab.SIC ,
       ab.OwnershipCode ,
       ab.MarketCap ,
       ab.SharesOutstanding ,
       ab.TickerSymbol ,
       ab.StockExchange ,
       ab.WebSiteURL ,
       ab.FtpSiteURL ,
       ab.EMailAddress1 ,
       ab.EMailAddress2 ,
       ab.EMailAddress3 ,
       ab.DoNotPhone ,
       ab.DoNotFax ,
       ab.Telephone1 ,
       ab.DoNotEMail ,
       ab.Telephone2 ,
       ab.Fax ,
       ab.Telephone3 ,
       ab.DoNotPostalMail ,
       ab.DoNotBulkEMail ,
       ab.DoNotBulkPostalMail ,
       ab.CreditLimit ,
       ab.CreditOnHold ,
       ab.IsPrivate ,
       ab.CreatedOn ,
       ab.CreatedBy ,
       ab.ModifiedOn ,
       ab.ModifiedBy ,
       ab.VersionNumber ,
       ab.ParentAccountId ,
       ab.Aging30 ,
       ab.StateCode ,
       ab.Aging60 ,
       ab.StatusCode ,
       ab.Aging90 ,
       ab.PreferredAppointmentDayCode ,
       ab.PreferredSystemUserId ,
       ab.PreferredAppointmentTimeCode ,
       ab.Merged ,
       ab.DoNotSendMM ,
       ab.MasterId ,
       ab.LastUsedInCampaign ,
       ab.PreferredServiceId ,
       ab.PreferredEquipmentId ,
       ab.ExchangeRate ,
       ab.UTCConversionTimeZoneCode ,
       ab.OverriddenCreatedOn ,
       ab.TimeZoneRuleVersionNumber ,
       ab.ImportSequenceNumber ,
       ab.TransactionCurrencyId ,
       ab.CreditLimit_Base ,
       ab.Aging30_Base ,
       ab.Revenue_Base ,
       ab.Aging90_Base ,
       ab.MarketCap_Base ,
       ab.Aging60_Base ,
       ab.YomiName ,
       ab.OwnerId ,
       ab.ModifiedOnBehalfBy ,
       ab.CreatedOnBehalfBy ,
       ab.OwnerIdType ,
       ab.StageId ,
       ab.ProcessId ,
       ab.EntityImageId ,
       ab.kore_ExternalAccountID ,
       ab.KORE_AgencyId ,
       ab.kore_billingcontactid ,
       ab.kore_countryid ,
       ab.kore_industryid ,
       ab.kore_stateorprovinceid ,
       ab.kore_salespersonid ,
       ab.kore_coordinatorid ,
       ab.koreps_PremiumSalespersonId ,
       ab.koreps_PremiumCoordinatorId ,
       ab.koreps_StrippedName ,
       ab.koreps_FutureLTV ,
       ab.koreps_futureltv_Base ,
       ab.koreps_LTVToDate ,
       ab.koreps_ltvtodate_Base ,
       ab.koreps_TotalLifetimeValue ,
       ab.koreps_totallifetimevalue_Base ,
       ab.str_clientpremiumsalespersonid ,
       ab.str_clientpremiumservicepersonid ,
       ab.str_clientpartnersalespersonid ,
       ab.str_clientpartnerservicepersonid ,
       ab.koreps_CheckedOutUntil ,
       ab.koreps_DoNotStream ,
       ab.koreps_FinanceAccountNumber ,
       ab.koreps_FinanceIsSynced ,
       ab.koreps_financemodifieddate ,
       ab.koreps_HasCheckedOutContact ,
       ab.koreps_LastContacted ,
       ab.koreps_numberofcontacts ,
       ab.koreps_CheckedOutBy ,
       ab.str_league1 ,
       ab.str_league2 ,
       ab.str_league3 ,
       ab.str_league4 ,
       ab.str_league5 ,
       ab.str_league6 ,
       ab.str_League7 ,
       ab.str_league8 ,
       ab.koreps_CurrentlyBeingWorked ,
       ab.koreps_MilesFromFacility ,
       ab.koreps_LastContactedById ,
       ab.koreps_SyncPriority ,
       cab.ParentId ,
       cab.CustomerAddressId ,
       cab.AddressNumber ,
       cab.ObjectTypeCode ,
       cab.AddressTypeCode ,
       cab.PrimaryContactName ,
       cab.Line1 ,
       cab.Line2 ,
       cab.Line3 ,
       cab.City ,
       cab.StateOrProvince ,
       cab.County ,
       cab.Country ,
       cab.PostOfficeBox ,
       cab.PostalCode
      FROM dbo.accountbase_20160930 ab
LEFT JOIN dbo.CustomerAddressBase_20160930 cab ON ab.AccountId = cab.ParentId
LEFT JOIN prodcopy.account pa ON ab.AccountId = pa.accountid
WHERE (ab.str_clientpremiumsalespersonid IS NOT NULL OR ab.str_clientpremiumservicepersonid IS NOT NULL OR ab.str_clientpartnerservicepersonid IS NOT NULL
OR ab.str_clientpartnersalespersonid IS NOT NULL) AND cab.AddressNumber = 1
AND pa.accountid IS NOT null

GO
