CREATE TABLE [dbo].[Kore_LeadBase]
(
[LeadId] [uniqueidentifier] NOT NULL,
[LeadSourceCode] [int] NULL,
[LeadQualityCode] [int] NULL,
[PriorityCode] [int] NULL,
[IndustryCode] [int] NULL,
[PreferredContactMethodCode] [int] NULL,
[SalesStageCode] [int] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[Subject] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParticipatesInWorkflow] [bit] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstimatedValue] [float] NULL,
[EstimatedCloseDate] [datetime] NULL,
[CompanyName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revenue] [money] NULL,
[NumberOfEmployees] [int] NULL,
[DoNotPhone] [bit] NULL,
[SIC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotFax] [bit] NULL,
[EMailAddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotEMail] [bit] NULL,
[EMailAddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPostalMail] [bit] NULL,
[EMailAddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiFirstName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WebSiteUrl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOn] [datetime] NULL,
[IsPrivate] [bit] NULL,
[Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiMiddleName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiLastName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[YomiFullName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [int] NOT NULL,
[Pager] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StatusCode] [int] NULL,
[VersionNumber] [timestamp] NULL,
[MasterId] [uniqueidentifier] NULL,
[CampaignId] [uniqueidentifier] NULL,
[DoNotSendMM] [bit] NULL,
[Merged] [bit] NULL,
[DoNotBulkEMail] [bit] NULL,
[LastUsedInCampaign] [datetime] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[ImportSequenceNumber] [int] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[ExchangeRate] [decimal] (23, 10) NULL,
[EstimatedAmount] [money] NULL,
[EstimatedAmount_Base] [money] NULL,
[Revenue_Base] [money] NULL,
[YomiCompanyName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsAutoCreate] [bit] NULL,
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[OwnerId] [uniqueidentifier] NOT NULL,
[CustomerId] [uniqueidentifier] NULL,
[CustomerIdType] [int] NULL,
[CustomerIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdType] [int] NOT NULL,
[CustomerIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StageId] [uniqueidentifier] NULL,
[DecisionMaker] [bit] NULL,
[Need] [int] NULL,
[BudgetAmount] [money] NULL,
[QualificationComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QualifyingOpportunityId] [uniqueidentifier] NULL,
[ScheduleFollowUp_Qualify] [datetime] NULL,
[ConfirmInterest] [bit] NULL,
[ParentAccountId] [uniqueidentifier] NULL,
[OriginatingCaseId] [uniqueidentifier] NULL,
[ScheduleFollowUp_Prospect] [datetime] NULL,
[EntityImageId] [uniqueidentifier] NULL,
[ParentContactId] [uniqueidentifier] NULL,
[InitialCommunication] [int] NULL,
[SalesStage] [int] NULL,
[BudgetStatus] [int] NULL,
[ProcessId] [uniqueidentifier] NULL,
[PurchaseTimeFrame] [int] NULL,
[PurchaseProcess] [int] NULL,
[RelatedObjectId] [uniqueidentifier] NULL,
[EvaluateFit] [bit] NULL,
[BudgetAmount_Base] [money] NULL,
[kore_CustNameID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ExternalLeadID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_TicketingAccountID] [int] NULL,
[kore_TicketingContractType] [int] NULL,
[kore_AccountId] [uniqueidentifier] NULL,
[kore_ContactId] [uniqueidentifier] NULL,
[kore_countryid] [uniqueidentifier] NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[koreps_AccountStrippedName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_TicketingAccountID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_DoNotStream] [bit] NULL,
[koreps_SyncPriority] [int] NULL
)
GO
ALTER TABLE [dbo].[Kore_LeadBase] ADD CONSTRAINT [cndx_PrimaryKey_Lead] PRIMARY KEY CLUSTERED  ([LeadId])
GO
