CREATE TABLE [dbo].[OpportunityBase]
(
[OpportunityId] [uniqueidentifier] NOT NULL,
[PriceLevelId] [uniqueidentifier] NULL,
[OpportunityRatingCode] [int] NULL,
[PriorityCode] [int] NULL,
[Name] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StepId] [uniqueidentifier] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstimatedValue] [money] NULL,
[StepName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesStageCode] [int] NULL,
[ParticipatesInWorkflow] [bit] NULL,
[PricingErrorCode] [int] NULL,
[EstimatedCloseDate] [datetime] NULL,
[CloseProbability] [int] NULL,
[ActualValue] [money] NULL,
[ActualCloseDate] [datetime] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[OriginatingLeadId] [uniqueidentifier] NULL,
[CreatedOn] [datetime] NULL,
[IsPrivate] [bit] NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[VersionNumber] [timestamp] NULL,
[StateCode] [int] NOT NULL,
[StatusCode] [int] NULL,
[IsRevenueSystemCalculated] [bit] NULL,
[CampaignId] [uniqueidentifier] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[ExchangeRate] [decimal] (23, 10) NULL,
[ImportSequenceNumber] [int] NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[ActualValue_Base] [money] NULL,
[EstimatedValue_Base] [money] NULL,
[TotalDiscountAmount] [money] NULL,
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[TotalAmount] [money] NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[TotalAmountLessFreight] [money] NULL,
[TotalLineItemDiscountAmount] [money] NULL,
[CustomerId] [uniqueidentifier] NULL,
[DiscountAmount] [money] NULL,
[OwnerId] [uniqueidentifier] NOT NULL,
[FreightAmount] [money] NULL,
[TotalTax] [money] NULL,
[DiscountPercentage] [decimal] (23, 10) NULL,
[TotalLineItemAmount] [money] NULL,
[CustomerIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerIdType] [int] NULL,
[OwnerIdType] [int] NOT NULL,
[TotalDiscountAmount_Base] [money] NULL,
[FreightAmount_Base] [money] NULL,
[TotalLineItemAmount_Base] [money] NULL,
[TotalTax_Base] [money] NULL,
[TotalLineItemDiscountAmount_Base] [money] NULL,
[TotalAmount_Base] [money] NULL,
[DiscountAmount_Base] [money] NULL,
[TotalAmountLessFreight_Base] [money] NULL,
[CustomerIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileDebrief] [bit] NULL,
[BudgetStatus] [int] NULL,
[PresentProposal] [bit] NULL,
[SendThankYouNote] [bit] NULL,
[EvaluateFit] [bit] NULL,
[FinalDecisionDate] [datetime] NULL,
[ConfirmInterest] [bit] NULL,
[CompleteInternalReview] [bit] NULL,
[TimeLine] [int] NULL,
[CustomerPainPoints] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResolveFeedback] [bit] NULL,
[QuoteComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchaseProcess] [int] NULL,
[CaptureProposalFeedback] [bit] NULL,
[ParentContactId] [uniqueidentifier] NULL,
[IdentifyCustomerContacts] [bit] NULL,
[CompleteFinalProposal] [bit] NULL,
[BudgetAmount] [money] NULL,
[ParentAccountId] [uniqueidentifier] NULL,
[ScheduleFollowup_Qualify] [datetime] NULL,
[Need] [int] NULL,
[PursuitDecision] [bit] NULL,
[ProcessId] [uniqueidentifier] NULL,
[ScheduleProposalMeeting] [datetime] NULL,
[StageId] [uniqueidentifier] NULL,
[QualificationComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesStage] [int] NULL,
[InitialCommunication] [int] NULL,
[IdentifyPursuitTeam] [bit] NULL,
[ScheduleFollowup_Prospect] [datetime] NULL,
[PurchaseTimeframe] [int] NULL,
[IdentifyCompetitors] [bit] NULL,
[DecisionMaker] [bit] NULL,
[CurrentSituation] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerNeed] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProposedSolution] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PresentFinalProposal] [bit] NULL,
[DevelopProposal] [bit] NULL,
[BudgetAmount_Base] [money] NULL
)
GO
ALTER TABLE [dbo].[OpportunityBase] ADD CONSTRAINT [cndx_PrimaryKey_Opportunity] PRIMARY KEY CLUSTERED  ([OpportunityId])
GO
