CREATE TABLE [dbo].[AccountBase_20160928]
(
[AccountId] [uniqueidentifier] NOT NULL,
[AccountCategoryCode] [int] NULL,
[TerritoryId] [uniqueidentifier] NULL,
[DefaultPriceLevelId] [uniqueidentifier] NULL,
[CustomerSizeCode] [int] NULL,
[PreferredContactMethodCode] [int] NULL,
[CustomerTypeCode] [int] NULL,
[AccountRatingCode] [int] NULL,
[IndustryCode] [int] NULL,
[TerritoryCode] [int] NULL,
[AccountClassificationCode] [int] NULL,
[BusinessTypeCode] [int] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[OriginatingLeadId] [uniqueidentifier] NULL,
[PaymentTermsCode] [int] NULL,
[ShippingMethodCode] [int] NULL,
[PrimaryContactId] [uniqueidentifier] NULL,
[ParticipatesInWorkflow] [bit] NULL CONSTRAINT [Set_To_Zero93] DEFAULT ((0)),
[Name] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountNumber] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revenue] [money] NULL,
[NumberOfEmployees] [int] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SIC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnershipCode] [int] NULL,
[MarketCap] [money] NULL,
[SharesOutstanding] [int] NULL,
[TickerSymbol] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockExchange] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WebSiteURL] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FtpSiteURL] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPhone] [bit] NULL CONSTRAINT [DF_AccountBase_DoNotPhone] DEFAULT ((0)),
[DoNotFax] [bit] NULL CONSTRAINT [DF_AccountBase_DoNotFax] DEFAULT ((0)),
[Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotEMail] [bit] NULL CONSTRAINT [DF_AccountBase_DoNotEMail] DEFAULT ((0)),
[Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPostalMail] [bit] NULL CONSTRAINT [DF_AccountBase_DoNotPostalMail] DEFAULT ((0)),
[DoNotBulkEMail] [bit] NULL CONSTRAINT [DF_AccountBase_DoNotBulkEMail] DEFAULT ((0)),
[DoNotBulkPostalMail] [bit] NULL CONSTRAINT [DF_AccountBase_DoNotBulkPostalMail] DEFAULT ((0)),
[CreditLimit] [money] NULL,
[CreditOnHold] [bit] NULL,
[IsPrivate] [bit] NULL CONSTRAINT [Set_To_Zero94] DEFAULT ((0)),
[CreatedOn] [datetime] NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[VersionNumber] [timestamp] NULL,
[ParentAccountId] [uniqueidentifier] NULL,
[Aging30] [money] NULL,
[StateCode] [int] NOT NULL,
[Aging60] [money] NULL,
[StatusCode] [int] NULL,
[Aging90] [money] NULL,
[PreferredAppointmentDayCode] [int] NULL,
[PreferredSystemUserId] [uniqueidentifier] NULL,
[PreferredAppointmentTimeCode] [int] NULL,
[Merged] [bit] NULL CONSTRAINT [DF_AccountBase_Merged] DEFAULT ((0)),
[DoNotSendMM] [bit] NULL CONSTRAINT [DF_AccountBase_DoNotSendMM] DEFAULT ((0)),
[MasterId] [uniqueidentifier] NULL,
[LastUsedInCampaign] [datetime] NULL,
[PreferredServiceId] [uniqueidentifier] NULL,
[PreferredEquipmentId] [uniqueidentifier] NULL,
[ExchangeRate] [decimal] (23, 10) NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[ImportSequenceNumber] [int] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[CreditLimit_Base] [money] NULL,
[Aging30_Base] [money] NULL,
[Revenue_Base] [money] NULL,
[Aging90_Base] [money] NULL,
[MarketCap_Base] [money] NULL,
[Aging60_Base] [money] NULL,
[YomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [uniqueidentifier] NOT NULL CONSTRAINT [DF_AccountBase_OwnerId] DEFAULT ('00000000-0000-0000-0000-000000000000'),
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[OwnerIdType] [int] NOT NULL CONSTRAINT [DF_AccountBase_OwnerIdType] DEFAULT ((8)),
[StageId] [uniqueidentifier] NULL,
[ProcessId] [uniqueidentifier] NULL,
[EntityImageId] [uniqueidentifier] NULL,
[kore_ExternalAccountID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_AgencyId] [uniqueidentifier] NULL,
[kore_billingcontactid] [uniqueidentifier] NULL,
[kore_countryid] [uniqueidentifier] NULL,
[kore_industryid] [uniqueidentifier] NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_salespersonid] [uniqueidentifier] NULL,
[kore_coordinatorid] [uniqueidentifier] NULL,
[koreps_PremiumSalespersonId] [uniqueidentifier] NULL,
[koreps_PremiumCoordinatorId] [uniqueidentifier] NULL,
[koreps_StrippedName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_FutureLTV] [money] NULL,
[koreps_futureltv_Base] [money] NULL,
[koreps_LTVToDate] [money] NULL,
[koreps_ltvtodate_Base] [money] NULL,
[koreps_TotalLifetimeValue] [money] NULL,
[koreps_totallifetimevalue_Base] [money] NULL,
[str_clientpremiumsalespersonid] [uniqueidentifier] NULL,
[str_clientpremiumservicepersonid] [uniqueidentifier] NULL,
[str_clientpartnersalespersonid] [uniqueidentifier] NULL,
[str_clientpartnerservicepersonid] [uniqueidentifier] NULL,
[koreps_CheckedOutUntil] [datetime] NULL,
[koreps_DoNotStream] [bit] NULL,
[koreps_FinanceAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_FinanceIsSynced] [bit] NULL,
[koreps_financemodifieddate] [datetime] NULL,
[koreps_HasCheckedOutContact] [bit] NULL,
[koreps_LastContacted] [datetime] NULL,
[koreps_numberofcontacts] [int] NULL,
[koreps_CheckedOutBy] [uniqueidentifier] NULL,
[str_league1] [int] NULL,
[str_league2] [int] NULL,
[str_league3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_league4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_league5] [int] NULL,
[str_league6] [int] NULL,
[str_League7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_league8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_CurrentlyBeingWorked] [bit] NULL,
[koreps_MilesFromFacility] [decimal] (23, 10) NULL,
[koreps_LastContactedById] [uniqueidentifier] NULL,
[koreps_SyncPriority] [int] NULL
)
GO
ALTER TABLE [dbo].[AccountBase_20160928] ADD CONSTRAINT [cndx_PrimaryKey_Account_20160928] PRIMARY KEY CLUSTERED  ([AccountId])
GO
