CREATE TABLE [ods].[Emma_Members]
(
[AccountID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MemberID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConfirmedOptIn] [datetime2] NULL,
[LastModifiedAt] [datetime2] NULL,
[MemberStatusID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlainTextPreferred] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailError] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberSince] [datetime2] NULL,
[BounceCount] [int] NULL,
[DeletedAt] [datetime2] NULL,
[FullName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [date] NULL,
[Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryEmail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchticsID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBTMSinceDate] [date] NULL,
[SSBIsNewRecord] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBRecordSource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBCRMSystemContactID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBBulldog] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSeasonTicketHolder] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBPartialPlanBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBClubTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSuiteTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBGroupTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSingleGameTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBParkingBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBMostRecentEvent] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBNextEvent] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSeatLocation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSeatQty] [int] NULL,
[AccountRepName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountRepEmail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountRepPhone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctRepFullName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctRepEmail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcctRepPhone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchiveProductTag] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B2BLink] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[B2BCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductTag] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberTickets] [int] NULL,
[SelectASeatTime] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialOfferLink] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialOfferCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Combinedlink] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArenaProductTag] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanEventCode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SegmentType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurveyLink] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_CreatedOn] [datetime] NOT NULL,
[ETL_CreatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL_UpdatedOn] [datetime] NOT NULL,
[ETL_UpdatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [ods].[Emma_Members] ADD CONSTRAINT [PK__Emma_Mem__A452A135C20EE26F] PRIMARY KEY CLUSTERED  ([AccountID], [MemberID])
GO
