CREATE TABLE [ods].[Emma_Contacts_Outbound_Json_Payload]
(
[SSB_CRMSYSTEM_CONTACT_ID] [uniqueidentifier] NULL,
[Email] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [date] NULL,
[Address] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBRecordSource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBIsNewRecord] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryEmail] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyName] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MemberID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArchticsID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountRepName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountRepEmail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountRepPhone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBBulldog] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSeasonTicketHolder] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBPartialPlanBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBClubTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSuiteTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBGroupTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSingleGameTicketBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBParkingBuyer] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBMostRecentEvent] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBNextEvent] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSeatLocation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSBSeatQty] [int] NULL,
[SSBTMSinceDate] [date] NULL,
[QueueID] [int] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL_DeltaHashKey] [binary] (32) NULL
)
GO
